### ISSUE TITLE
Automatically create a job matrix

### ISSUE THREAD

**Issue by Emiller88** [askimed/nf-test#102]
I'd love to be able to automate a job matrix for our nf-core jobs. Kinda similar to https://github.com/askimed/nf-test/issues/38

Right now we're either running all the tests on one runner:
```yaml
      # Run nf-test
      - name: Run nf-test
        run: nf-test test tests/pipeline/ --profile=test,${{ matrix.profile }} --junitxml=test.xml
```
For each container profile

Or we're creating a strategy like:
```yaml
    strategy:
      fail-fast: false
      matrix:
        NXF_VER:
          - "22.10.1"
          - "latest-everything"
        aligner:
          - "bismark"
          - "bismark_hisat"
          - "bwameth"
        profile:
          - "docker"
```

And testing with
```yaml
      - name: Run nf-test
        if: steps.condition.outputs.skip != 'true'
        run: |
          nf-test test tests/pipeline/${{ matrix.aligner }}/ --profile "test,${{ matrix.profile }}" --tap=test.tap
```

So it requires quite a bit of manual work to keep up with the CI testing right now and keep it flowing smoothly.

I'm thinking if we could list all the tags with a `nf-test list tags` then we could pull in all the tags and run those separately by default and then use the GH actions `include:` to get cross-overs of tags or whatever. Then we'd be able to do something like [this](https://github.com/nf-core/demultiplex/blob/21dad4b89a6d6994e660aa158da18f6499d93e83/.github/workflows/ci.yml#L21-L33) to automate the job creation, of one GH job per nf-test tag.

But I guess I could hack something together with `nf-test list` right now to just run every test separately 🤔
