### ISSUE TITLE
support for loading multiline strings in yaml params files

### ISSUE THREAD

**Issue by seanrjohnson** [askimed/nf-test#257]
For pipeline tests, the params load config file function parses multiline strings in yml files differently than supplying them to nextFlow via the command line `-params-file` option.

```groovy
params {
   load("example_params.yml")
}
```

```
Json file parsed correctly:
```json
{
  "query_sequence": ">A0A2G2JID1\nMPIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR\n>A0A8G5FSM5\nMPIAQLYILEGRSDEQKESLIREISEAMSRSLDAPIERVRVIITEMPKNHFGIGGEPASKLNR\n>A0A0F9USC8\nMPIAQLHILEGRTDEQKEALIREVSEAIARALDAPMPSIRVIISEMPKAHFGIGGEPASKVRR\n>A0A3S8ND41\nMPVAQINILEGRSDEQKETLIREVSEAISRSLGAPVENVRIIITEMPKQHFGIGGQSAKKRGR\n",
  "query_file": null,
  "identity": 100,
  "fasta_type": "protein",
  "algorithm": "cd-hit",
  "output_type": "genbank",
  "count": "prefix"
}
```

.yml file not parsed correctly (deletes newlines in "query_sequence"):
```yaml
query_sequence: ">A0A2G2JID1\nMPIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR\n>A0A8G5FSM5\nMPIAQLYILEGRSDEQKESLIREISEAMSRSLDAPIERVRVIITEMPKNHFGIGGEPASKLNR\n>A0A0F9USC8\nMPIAQLHILEGRTDEQKEALIREVSEAIARALDAPMPSIRVIISEMPKAHFGIGGEPASKVRR\n>A0A3S8ND41\nMPVAQINILEGRSDEQKETLIREVSEAISRSLGAPVENVRIIITEMPKQHFGIGGQSAKKRGR\n"
query_file:
identity: 100
fasta_type: protein
algorithm: cd-hit
output_type: genbank
count: prefix
```
.yml file also not parsed correctly (deletes newlines in "query_sequence"):
```
query_sequence: |
  >A0A2G2JID1
  MPIAQIHILEGRSDEQKETLIREVSEAISRSLDAPLTSVRVIITEMAKGHFGIGGELASKVRR
  >A0A8G5FSM5
  MPIAQLYILEGRSDEQKESLIREISEAMSRSLDAPIERVRVIITEMPKNHFGIGGEPASKLNR
  >A0A0F9USC8
  MPIAQLHILEGRTDEQKEALIREVSEAIARALDAPMPSIRVIISEMPKAHFGIGGEPASKVRR
  >A0A3S8ND41
  MPVAQINILEGRSDEQKETLIREVSEAISRSLGAPVENVRIIITEMPKQHFGIGGQSAKKRGR
query_file:
identity: 100
fasta_type: protein
algorithm: cd-hit
output_type: genbank
count: prefix
```
